/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'watch-models': WatchModel;
    'watch-straps': WatchStrap;
    'strap-params': StrapParam;
    'additional-options': AdditionalOption;
    'promo-codes': PromoCode;
    media: Media;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'watch-models': WatchModelsSelect<false> | WatchModelsSelect<true>;
    'watch-straps': WatchStrapsSelect<false> | WatchStrapsSelect<true>;
    'strap-params': StrapParamsSelect<false> | StrapParamsSelect<true>;
    'additional-options': AdditionalOptionsSelect<false> | AdditionalOptionsSelect<true>;
    'promo-codes': PromoCodesSelect<false> | PromoCodesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-models".
 */
export interface WatchModel {
  id: string;
  /**
   * Уникальное имя модели (например, apple-watch-ultra-2)
   */
  model_name: string;
  /**
   * Отображаемое название (например, Apple Watch Ultra 2)
   */
  watch_model_name: string;
  /**
   * Название производителя (например, Apple)
   */
  watch_model_manufacturer?: string | null;
  main_image?: (string | null) | Media;
  watch_sizes: {
    /**
     * Размер в мм (например, 42, 44, 49)
     */
    watch_size: string;
    id?: string | null;
  }[];
  frame_colors: {
    color_name: string;
    /**
     * Например: #C0C0C0
     */
    color_code?: string | null;
    id?: string | null;
  }[];
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-straps".
 */
export interface WatchStrap {
  id: string;
  /**
   * Уникальное имя ремешка (например, brogue, classic)
   */
  strap_name: string;
  /**
   * Отображаемое название (например, Brogue, Classic)
   */
  strap_title: string;
  strap_description?:
    | {
        [k: string]: unknown;
      }[]
    | null;
  strap_short_description?: string | null;
  price: number;
  preview_image?: (string | null) | Media;
  ultra_preview_image?: (string | null) | Media;
  has_buckle_butterfly?: boolean | null;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strap-params".
 */
export interface StrapParam {
  id: string;
  watch_strap: string | WatchStrap;
  strap_name: string;
  leather_colors?:
    | {
        color_title: string;
        color_code?: string | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  stitching_colors?:
    | {
        color_title: string;
        color_code?: string | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  edge_colors?:
    | {
        color_title: string;
        color_code?: string | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  buckle_colors?:
    | {
        color_title: string;
        color_code?: string | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  adapter_colors?:
    | {
        color_title: string;
        color_code?: string | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  buckle_butterfly_price?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "additional-options".
 */
export interface AdditionalOption {
  id: string;
  title: string;
  description?: string | null;
  additional_options?:
    | {
        /**
         * initials, presentBox, postCard
         */
        option_name: string;
        option_title: string;
        option_description?: string | null;
        option_placeholder?: string | null;
        option_price: number;
        option_type: 'checkbox' | 'text' | 'textarea';
        is_active?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes".
 */
export interface PromoCode {
  id: string;
  /**
   * Уникальный код промокода (например, SUMMER2025)
   */
  code: string;
  discount_type: 'percent' | 'ruble';
  /**
   * Процент (1-100) или сумма в рублях
   */
  discount_value: number;
  min_order_amount?: number | null;
  valid_from?: string | null;
  valid_until?: string | null;
  /**
   * Оставьте пустым для неограниченного использования
   */
  usage_limit?: number | null;
  usage_count?: number | null;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'watch-models';
        value: string | WatchModel;
      } | null)
    | ({
        relationTo: 'watch-straps';
        value: string | WatchStrap;
      } | null)
    | ({
        relationTo: 'strap-params';
        value: string | StrapParam;
      } | null)
    | ({
        relationTo: 'additional-options';
        value: string | AdditionalOption;
      } | null)
    | ({
        relationTo: 'promo-codes';
        value: string | PromoCode;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-models_select".
 */
export interface WatchModelsSelect<T extends boolean = true> {
  model_name?: T;
  watch_model_name?: T;
  watch_model_manufacturer?: T;
  main_image?: T;
  watch_sizes?:
    | T
    | {
        watch_size?: T;
        id?: T;
      };
  frame_colors?:
    | T
    | {
        color_name?: T;
        color_code?: T;
        id?: T;
      };
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "watch-straps_select".
 */
export interface WatchStrapsSelect<T extends boolean = true> {
  strap_name?: T;
  strap_title?: T;
  strap_description?: T;
  strap_short_description?: T;
  price?: T;
  preview_image?: T;
  ultra_preview_image?: T;
  has_buckle_butterfly?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strap-params_select".
 */
export interface StrapParamsSelect<T extends boolean = true> {
  watch_strap?: T;
  strap_name?: T;
  leather_colors?:
    | T
    | {
        color_title?: T;
        color_code?: T;
        price?: T;
        id?: T;
      };
  stitching_colors?:
    | T
    | {
        color_title?: T;
        color_code?: T;
        price?: T;
        id?: T;
      };
  edge_colors?:
    | T
    | {
        color_title?: T;
        color_code?: T;
        price?: T;
        id?: T;
      };
  buckle_colors?:
    | T
    | {
        color_title?: T;
        color_code?: T;
        price?: T;
        id?: T;
      };
  adapter_colors?:
    | T
    | {
        color_title?: T;
        color_code?: T;
        price?: T;
        id?: T;
      };
  buckle_butterfly_price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "additional-options_select".
 */
export interface AdditionalOptionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  additional_options?:
    | T
    | {
        option_name?: T;
        option_title?: T;
        option_description?: T;
        option_placeholder?: T;
        option_price?: T;
        option_type?: T;
        is_active?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promo-codes_select".
 */
export interface PromoCodesSelect<T extends boolean = true> {
  code?: T;
  discount_type?: T;
  discount_value?: T;
  min_order_amount?: T;
  valid_from?: T;
  valid_until?: T;
  usage_limit?: T;
  usage_count?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}